import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { PhaseTwoClearPractice } from './PhaseTwoClearPractice'
const api=vi.hoisted(()=>({load:vi.fn(),save:vi.fn()}))
vi.mock('./phaseTwoProject',()=>({loadPhaseTwoProject:api.load,savePhaseTwoProjectUpdate:api.save}))
const request='Critique this draft under Correct, Listener, Enough, Appropriate and Responsible. Flag unsupported claims and missing information. Do not assert that facts are verified. Draft and approved sources: [inputs].'
beforeEach(()=>{vi.clearAllMocks();api.load.mockResolvedValue({project_path:'B',project_title:'Existing project',sections:{}});api.save.mockResolvedValue({saved_version:10})})
it('keeps review copy-only and preserves critique and approval limits',()=>{
 render(<PhaseTwoClearPractice approvedAiRequest={request}/> )
 expect(screen.queryByRole('button',{name:'Save CLEAR evidence to My Project Record'})).toBeNull()
 fireEvent.change(screen.getByLabelText('Communication from Lesson 2.2 to review'),{target:{value:'Delivery in five days.'}})
 expect((screen.getByLabelText('CLEAR critique request') as HTMLTextAreaElement).value).toContain('Delivery in five days.')
 expect((screen.getByLabelText('CLEAR critique request') as HTMLTextAreaElement).value).toContain('Do not assert that facts are verified.')
 expect(screen.queryByRole('button',{name:/send message|approve communication/i})).toBeNull()
})
it('carries the saved 2.2 revision forward and saves 2.3 in its own nested entry',async()=>{
 api.load.mockResolvedValue({project_path:'B',project_title:'Existing project',sections:{prompt_and_communication_evidence:{communication_lesson_2_2:{draft:{revised:'Retained 2.2 communication',audience:'Customer',purpose:'Collect details',response:'Reply'}}}}})
 render(<PhaseTwoClearPractice approvedAiRequest={request} enrollmentId="existing-enrollment"/> )
 const button=await screen.findByRole('button',{name:'Save CLEAR evidence to My Project Record'})
 await waitFor(()=>expect((screen.getByLabelText('Communication from Lesson 2.2 to review') as HTMLTextAreaElement).value).toBe('Retained 2.2 communication'))
 expect((button as HTMLButtonElement).disabled).toBe(true)
 screen.getAllByRole('textbox').filter(el=>!(el as HTMLTextAreaElement).readOnly).forEach((el,i)=>fireEvent.change(el,{target:{value:'Evidence '+i}}))
 fireEvent.click(button)
 await waitFor(()=>expect(api.save).toHaveBeenCalledTimes(1))
 const input=api.save.mock.calls[0][0]
 expect(input.path).toBe('B');expect(input.title).toBe('Existing project')
 expect(Object.keys(input.patch)).toEqual(['prompt_and_communication_evidence'])
 expect(Object.keys(input.patch.prompt_and_communication_evidence)).toEqual(['clear_lesson_2_3'])
 expect(input.patch.prompt_and_communication_evidence.clear_lesson_2_3.draft.checkedDate).toBeTruthy()
 expect(input.patch.prompt_and_communication_evidence.clear_lesson_2_3.practice_only_not_permission_to_send).toBe(true)
 await screen.findByText('Saved to your continuing Project Record. Version 10.')
})
it('restores the later CLEAR review instead of replacing it with the earlier draft',async()=>{
 api.load.mockResolvedValue({project_path:'A',project_title:'Existing project',sections:{prompt_and_communication_evidence:{clear_lesson_2_3:{draft:{original:'Reviewed before version',correct:'Source mismatch',approval:'Pending human approval'}},communication_lesson_2_2:{draft:{revised:'Earlier draft'}}}}})
 render(<PhaseTwoClearPractice approvedAiRequest={request} enrollmentId="existing-enrollment"/> )
 await waitFor(()=>expect((screen.getByLabelText('Communication from Lesson 2.2 to review') as HTMLTextAreaElement).value).toBe('Reviewed before version'))
 expect((screen.getByLabelText('Authorized human approver and actual approval status (or pending)') as HTMLTextAreaElement).value).toBe('Pending human approval')
 expect(api.save).not.toHaveBeenCalled()
})
it('retains answers and allows retry after a failed save',async()=>{
 api.save.mockRejectedValueOnce(new Error('Connection failed'))
 render(<PhaseTwoClearPractice approvedAiRequest={request} enrollmentId="existing-enrollment"/> )
 const button=await screen.findByRole('button',{name:'Save CLEAR evidence to My Project Record'})
 screen.getAllByRole('textbox').filter(el=>!(el as HTMLTextAreaElement).readOnly).forEach(el=>fireEvent.change(el,{target:{value:'Keep my review'}}))
 fireEvent.click(button)
 await screen.findByText('Save was unsuccessful. Your answers remain here; retry or copy your record.')
 expect((screen.getByLabelText('Revised communication') as HTMLTextAreaElement).value).toBe('Keep my review')
 fireEvent.click(button)
 await screen.findByText('Saved to your continuing Project Record. Version 10.')
})
