export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))

export function newsletterMessage(items, mailingAddress) {
  if (!String(mailingAddress || '').trim()) throw new Error('Academy mailing address is required')
  if (!Array.isArray(items) || !items.length) throw new Error('An update needs published content')
  for (const item of items) {
    const url = new URL(item.url)
    if(url.origin !== 'https://aiconfidenceacademy.org' || !item.title) throw new Error('Only published Academy links are allowed')
  }
  const unsubscribe = '{{{RESEND_UNSUBSCRIBE_URL}}}'
  const subject = 'New learning from AI Confidence Academy'
  const links = items.map(item=>`<tr><td style="padding-top:18px;padding-bottom:18px;border-bottom:1px solid #dfd3b7"><p style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#8a6728;margin-top:0;margin-bottom:6px">${item.kind==='video'?'WATCH & LEARN':'ACADEMY NOTE'}</p><a href="${escapeHtml(item.url)}" style="font-family:Georgia,serif;font-size:22px;line-height:30px;color:#102d50;text-decoration:underline">${escapeHtml(item.title)}</a></td></tr>`).join('')
  const html=`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>${subject}</title></head><body style="margin-top:0;margin-right:0;margin-bottom:0;margin-left:0;background-color:#f7f2e6"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" bgcolor="#f7f2e6" style="padding-top:28px;padding-bottom:28px;padding-left:12px;padding-right:12px;background-color:#f7f2e6"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px"><tr><td bgcolor="#102d50" style="background-color:#102d50;padding-top:26px;padding-bottom:26px;padding-left:28px;padding-right:28px"><p style="font-family:Georgia,serif;font-size:25px;line-height:32px;color:#ffffff;margin-top:0;margin-bottom:8px">AI Confidence Academy</p><p style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#e7c982;margin-top:0;margin-bottom:0">People First. AI Assist. Human Guide.</p></td></tr><tr><td bgcolor="#ffffff" style="background-color:#ffffff;padding-top:28px;padding-bottom:28px;padding-left:28px;padding-right:28px"><h1 style="font-family:Georgia,serif;font-size:28px;line-height:36px;color:#102d50;margin-top:0;margin-bottom:18px">A little learning. More possibilities.</h1><p style="font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:27px;color:#233d58">Thank you for staying connected with the Academy. Here are the latest additions for you to explore at your own pace.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">${links}</table><p style="font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:27px;color:#233d58">Thank you for joining us. We look forward to learning with you.</p><p style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#102d50">People come first. AI is the tool. Confidence is the product.</p></td></tr><tr><td bgcolor="#f7f2e6" style="background-color:#f7f2e6;padding-top:22px;padding-left:28px;padding-right:28px"><p style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:21px;color:#526070">You receive these optional updates because you signed up. Changing this preference does not change your enrollment, payment reminders, or lesson notices.</p><p style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:21px;color:#526070">AI Confidence Academy<br>${escapeHtml(mailingAddress)}</p><a href="${unsubscribe}" style="font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:24px;color:#102d50;text-decoration:underline">Manage updates or unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  const text=`AI Confidence Academy\nPeople First. AI Assist. Human Guide.\n\nThank you for staying connected. Explore the latest Academy additions at your own pace.\n\n${items.map(x=>`${x.title}\n${x.url}`).join('\n\n')}\n\nThank you for joining us. We look forward to learning with you.\n\nThese optional updates do not affect enrollment, payments, or lesson notices.\nAI Confidence Academy\n${mailingAddress}\nManage updates or unsubscribe: ${unsubscribe}`
  return {subject,html,text}
}
